version: "3.9"
services:
    app:
        build: .
        container_name: realara
        working_dir: /var/www/
        ports:
            - "5173:5173"
        volumes:
            - .:/var/www
        networks:
            - app-network
    db:
        image: mysql:latest
        container_name: mysql
        ports:
            - "23306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./database/data:/var/lib/mysql
        networks:
            - app-network
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8030:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
